platform:ios, "6.0"
inhibit_all_warnings!

pod "Reachability"
pod "MBProgressHUD"
pod 'AFNetworking-RACExtensions'
pod 'Nimbus/AttributedLabel'
pod 'FMDB'
pod 'CustomBadge'
pod 'SDWebImage'
pod 'ALToastView'
pod 'MessageDisplayKit'
